version: 0.0.1

achievements:

  - achievement:
      name: Code Initiate
      icon: https://raw.githubusercontent.com/CodeByPrakash/portfolio/main/public/achievements/code-initiate.svg
      description: Made your first contribution to the project.
      triggers:
        - trigger:
            actor: author
            action: commit
            condition: count() >= 1

  - achievement:
      name: Commit Warrior
      icon: https://raw.githubusercontent.com/CodeByPrakash/portfolio/main/public/achievements/commit-warrior.svg
      description: Reached 10 commits on the project.
      triggers:
        - trigger:
            actor: author
            action: commit
            condition: count() >= 10

  - achievement:
      name: PR Hero
      icon: https://raw.githubusercontent.com/CodeByPrakash/portfolio/main/public/achievements/pr-hero.svg
      description: Successfully merged a pull request.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: merged = true

  - achievement:
      name: Bug Hunter
      icon: https://raw.githubusercontent.com/CodeByPrakash/portfolio/main/public/achievements/bug-hunter.svg
      description: Successfully closed an issue.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: closed = true

  - achievement:
      name: Project Supporter
      icon: https://raw.githubusercontent.com/CodeByPrakash/portfolio/main/public/achievements/project-supporter.svg
      description: Starred the project.
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true