/**
 * ============================================================================
 * SEO KEYWORDS & SEARCH CONSOLE CONFIGURATION
 * ============================================================================
 * 
 * 💡 EASY WORDS / QUICK ADD SECTION:
 * You can easily add any new keyword, phrase, tag, or synonym to the `EASY_WORDS`
 * array below! Any word you add here is automatically included in your website's
 * SEO meta tags, Google Search Console discovery, and social preview metadata.
 * ============================================================================
 */

export const EASY_WORDS = [
  // ─── ADD YOUR EASY WORDS / PHRASES HERE ───
  'Om Prakash',
  'Prakash Behera',
  'CodeByPrakash',
  'Portfolio',
  'Developer Portfolio 2026',
  'Personal Website',
  'Hire Developer',
  'Hire AI Engineer',
  'Freelance Web Developer',
  'Student Developer',
  'Computer Science Graduate',
  'Full Stack Coder',
  'AI Builder',
  'Open Source Contributor',
  'Software Project Showcase',
  'Clean Code',
  'Creative Developer',
  'Tech Enthusiast',
  'Best Developer Portfolio',
  'Web App Creator',
  'VoxelCam',
  'VoxelCam 3D',
  '3D Voxel Camera',
  'voxelcam.vercel.app',
  'CodeByPrakash VoxelCam',
  'Real-Time 3D Pixel Blocks',
  'CyberTerminal OS',
  'Cyber Terminal Portfolio',
  'vintageprixu.vercel.app',
  'vintageprixu',
  'CLI Web Portfolio',
  'Command Line Interface Web Portfolio',
  'Terminal Portfolio Om Prakash',
  'CodeByPrakash CyberTerminal',
  'interactive terminal web portfolio',

  // ─── GAMING & GAMER SEARCH COMBINATIONS ───
  'omprakash gamer',
  'Om Prakash Gamer',
  'OmPrakash Gamer',
  'omprakash gaming',
  'Om Prakash Gaming',
  'omprakash pc gamer',
  'Om Prakash PC Gamer',
  'omprakash pro gamer',
  'omprakash esports',
  'CodeByPrakash Gaming',
  'CodeByPrakash Gamer',
  'Quasar Om Gamer',
  'Quasar Om Gaming',
  'quasar_om gamer',
  'quasar_om gaming',
  'omprakash gamer odisha',
  'omprakash gamer india',
  'omprakash yt gamer',
  'omprakash gameplay',

  // ─── PC & COMPUTER SEARCH COMBINATIONS ───
  'omprakash pc',
  'Om Prakash PC',
  'OmPrakash PC',
  'omprakash computer',
  'Om Prakash Computer',
  'OmPrakash Computer',
  'omprakash pc build',
  'omprakash pc setup',
  'omprakash computer science',
  'omprakash computer engineer',
  'omprakash computer programmer',
  'omprakash workstation',
  'omprakash laptop',
  'omprakash pc specs',
  'omprakash computer developer',
  'codebyprakash pc',
  'codebyprakash computer',

  // ─── DIPLOMA CSE & POLYTECHNIC SEARCH COMBINATIONS ───
  'diploma cse',
  'diploma in cse',
  'diploma computer science',
  'diploma in computer science engineering',
  'diploma computer science and engineering',
  'diploma in computer engineering',
  'diploma cse odisha',
  'diploma cse sctevt',
  'diploma cse distinction',
  'diploma cse topper',
  'diploma cse projects',
  'diploma cse lateral entry',
  'diploma cse to btech cse',
  'diploma cse ojee',
  'diploma cse student portfolio',
  'polytechnic cse',
  'polytechnic diploma cse',
  'polytechnic computer science',
  'omprakash diploma cse',
  'om prakash behera diploma cse',

  // ─── NAME + ROLE COMPOUND SEARCH PHRASES ───
  // (These match exactly how people search: "name + what they do")
  'Om Prakash Behera developer',
  'Om Prakash Behera portfolio',
  'Om Prakash Behera engineer',
  'Om Prakash Behera AI',
  'Om Prakash Behera projects',
  'Om Prakash Behera GitHub',
  'Om Prakash Behera resume',
  'Om Prakash Behera website',
  'Om Prakash developer India',
  'Om Prakash full stack developer',
  'Om Prakash Behera freelance',
  'Om Prakash Behera CSE',
  'Om Prakash Behera Odisha',
  'Om Prakash Behera GCEK',
  'Om Prakash Behera BTech',
  'Prakash Behera developer',
  'CodeByPrakash portfolio',
  'CodeByPrakash GitHub',
  'CodeByPrakash developer',

  // ─── GENERIC DISCOVERY PHRASES ───
  // (What someone types when looking for a dev to hire)
  'hire a developer',
  'hire a coder',
  'hire a programmer',
  'find a developer',
  'looking for developer',
  'need a web developer',
  'need an AI developer',
  'best student developer India',
  'top developer portfolio India',
  'developer for hire India',
  'young developer India',
  'college student developer',
  'engineering student projects',
  'BTech student portfolio',
  'CSE student portfolio',
  'fresher developer portfolio',
  'junior developer portfolio',
  'developer portfolio website',
  'software engineer portfolio',
  'programmer portfolio',
  'coder portfolio',
]

/**
 * ─── CATEGORIZED KEYWORD DICTIONARIES ───
 */

// 1. Identity & Name Variations
// Covers: exact name, misspellings, native scripts, social handles, name+location, name+role, name+context combos
export const IDENTITY_KEYWORDS = [
  // ─── Core Name Variations ───
  'Om Prakash Behera',
  'OmPrakash Behera',
  'Om Prakash',
  'Omprakash',
  'OMPRAKASH',
  'OMPRAKASH BEHERA',
  'OM PRAKASH BEHERA',
  'omprakash behera',
  'om prakash',
  'OM PRAKASH',
  'Om',
  'Prakash',
  'Behera',
  'CodeByPrakash',
  'Code By Prakash',
  'codebyprakash',
  'CODEBYPRAKASH',
  'Prakash Behera',
  'PrakashBehera',
  'Quasar Om',
  'quasar_om',
  'Quasar_Om',
  'QuasarOm',
  'quasarom',
  'omprakashbehera',
  'om prakash behera',
  'OM PRAKASH BEHERA',
  'O P Behera',
  'OP Behera',
  'O.P. Behera',
  'OPB',
  'opb',
  'Om Prakash CSE',
  'Omprakash CSE',
  'Prakash CSE',
  'Om Prakash GCEK',
  'Om Prakash Bhadrak',
  'Om Prakash Odisha',

  // ─── Odia Script Variations (Native Language Search) ───
  'ଓମ ପ୍ରକାଶ ବେହେରା',
  'ଓମ୍ ପ୍ରକାଶ ବେହେରା',
  'ଓମ୍ପ୍ରକାଶ ବେହେରା',
  'ଓମ ପ୍ରକାଶ',
  'ଓମ୍ ପ୍ରକାଶ',
  'ପ୍ରକାଶ ବେହେରା',
  'ଓଡ଼ିଆ ଡେଭଲପର',
  'ଓଡ଼ିଆ ଇଞ୍ଜିନିୟର',
  'ଓମ ପ୍ରକାଶ ବେହେରା ଭଦ୍ରକ',
  'ଓମ ପ୍ରକାଶ ବେହେରା କଳାହାଣ୍ଡି',

  // ─── Hindi Script Variations ───
  'ओम प्रकाश बेहरा',
  'ओमप्रकाश बेहरा',
  'ओम प्रकाश बेहेरा',
  'ओमप्रकाश बेहेरा',
  'प्रकाश बेहरा',
  'ओम प्रकाश',
  'ओमप्रकाश',

  // ─── Common Misspellings, Typos & Pronunciations ───
  'Om Prakash Behara',
  'Om Prakash Behra',
  'Om Praksh Behera',
  'Omprakash Behra',
  'Omprakash Behara',
  'Om Prakas Behera',
  'Om Prakash Behra developer',
  'Prakash Behara',
  'Prakash Behra',
  'Om Prakash Behera developer',
  'Omprakash B',
  'Om P Behera',
  'OmprakashB',
  'Om Prakash B',

  // ─── Direct Contact & Social Media Handles ───
  'omprakashbehera.me',
  'https://omprakashbehera.me',
  'omprakashbehera.cse@gmail.com',
  'omprakashbehera.cse',
  'CodeByPrakash GitHub',
  'CodeByPrakash portfolio',
  'CodeByPrakash developer',
  'CodeByPrakash Instagram',
  'CodeByPrakash LinkedIn',
  'CodeByPrakash projects',
  'CodeByPrakash repos',
  'github.com/CodeByPrakash',
  'linkedin.com/in/omprakash-cse',
  'omprakash-cse LinkedIn',
  'omprakash-cse',
  'instagram.com/quasar_om',
  'quasar_om Instagram',
  'quasar_om developer',
  '0009-0002-2403-2907',
  'ORCID 0009-0002-2403-2907',
  'ORCID Om Prakash Behera',

  // ─── Name + Location Combinations (Local Search) ───
  'Om Prakash Behera Odisha',
  'Om Prakash Behera Bhadrak',
  'Om Prakash Behera Bhawanipatna',
  'Om Prakash Behera Kalahandi',
  'Om Prakash Behera India',
  'Om Prakash Behera Bhubaneswar',
  'Om Prakash Behera Cuttack',
  'Om Prakash Behera Jaipatna',
  'Om Prakash Behera Balasore',
  'Om Prakash Behera Sambalpur',
  'Om Prakash Behera Rourkela',
  'Om Prakash GCEK',
  'Prakash Behera Odisha',
  'Prakash Behera Bhadrak',
  'Behera Odisha developer',
  'Bhadrak developer Om Prakash',
  'Kalahandi engineer Om Prakash',

  // ─── Name + Role Combinations ───
  'Om Prakash Behera software engineer',
  'Om Prakash Behera web developer',
  'Om Prakash Behera full stack developer',
  'Om Prakash Behera frontend developer',
  'Om Prakash Behera backend developer',
  'Om Prakash Behera python developer',
  'Om Prakash Behera react developer',
  'Om Prakash Behera AI developer',
  'Om Prakash Behera ML engineer',
  'Om Prakash Behera machine learning engineer',
  'Om Prakash Behera deep learning specialist',
  'Om Prakash Behera computer vision engineer',
  'Om Prakash Behera computer science engineer',
  'Om Prakash Behera cyber security enthusiast',
  'Om Prakash Behera ethical hacker',
  'Om Prakash Behera blockchain developer',
  'Om Prakash Behera data scientist',
  'Om Prakash Behera coder',
  'Om Prakash Behera programmer',
  'Om Prakash Behera freelancer',
  'Om Prakash developer India',
  'Om Prakash full stack developer',
  'Prakash Behera developer',
  'Prakash developer India',

  // ─── Name + Context & Biography Queries ───
  'Om Prakash Behera portfolio',
  'Om Prakash Behera website',
  'Om Prakash Behera resume',
  'Om Prakash Behera resume PDF',
  'Om Prakash Behera CV',
  'Om Prakash Behera projects',
  'Om Prakash Behera GitHub',
  'Om Prakash Behera blog',
  'Om Prakash Behera skills',
  'Om Prakash Behera experience',
  'Om Prakash Behera education',
  'Om Prakash Behera academics',
  'Om Prakash Behera achievements',
  'Om Prakash Behera awards',
  'Om Prakash Behera certifications',
  'Om Prakash Behera hackathon',
  'Om Prakash Behera ISRO',
  'Om Prakash Behera SIH',
  'Om Prakash Behera Smart India Hackathon',
  'Om Prakash Behera YOUTH 2050',
  'Om Prakash Behera BTech',
  'Om Prakash Behera CSE',
  'Om Prakash Behera diploma',
  'Om Prakash Behera GCEK',
  'Om Prakash Behera college',
  'Om Prakash Behera university',
  'Om Prakash Behera background',
  'Om Prakash Behera bio',
  'Om Prakash Behera biography',
  'Om Prakash Behera story',
  'Om Prakash Behera profile photo',
  'who is Om Prakash Behera',
  'who is CodeByPrakash',
  'about Om Prakash Behera',
  'Om Prakash Behera stats',

  // ─── Name + Contact / Hiring Queries ───
  'Om Prakash Behera contact',
  'Om Prakash Behera email',
  'Om Prakash Behera email address',
  'Om Prakash Behera phone',
  'Om Prakash Behera WhatsApp',
  'Om Prakash Behera message',
  'Om Prakash Behera hire',
  'Om Prakash Behera freelance',
  'Om Prakash Behera available',
  'Om Prakash Behera for hire',
  'contact Om Prakash Behera',
  'email Om Prakash Behera',
  'how to contact Om Prakash Behera',
  'hire Om Prakash',
  'hire Prakash Behera',
  'hire CodeByPrakash',
  'hire developer Om Prakash Behera',

  // ─── Gamer & Gaming Searches ───
  'omprakash gamer',
  'Om Prakash Gamer',
  'OmPrakash Gamer',
  'omprakash gaming',
  'Om Prakash Gaming',
  'OmPrakash Gaming',
  'omprakash pc gamer',
  'Om Prakash PC Gamer',
  'omprakash pro gamer',
  'omprakash esports',
  'CodeByPrakash Gaming',
  'CodeByPrakash Gamer',
  'Quasar Om Gamer',
  'Quasar Om Gaming',
  'quasar_om gamer',
  'quasar_om gaming',
  'Om Prakash game developer',
  'omprakash game dev',
  'omprakash games',
  'omprakash streamer',
  'omprakash gaming setup',
  'om gaming',
  'prakash gamer',
  'prakash gaming',
  'om gamer',
  'omprakash yt gamer',
  'omprakash gaming channel',
  'omprakash gameplay',
  'omprakash live gamer',
  'omprakash free fire',
  'omprakash bgmi',
  'omprakash gta',
  'omprakash valorant',
  'omprakash steam',
  'omprakash discord gamer',
  'omprakash gamer odisha',
  'omprakash gamer india',
  'omprakashgamer',
  'omprakashgaming',
  'OMPRAKASH GAMER',
  'OMPRAKASH GAMING',
  'om_prakash_gamer',
  'quasar_om_gamer',

  // ─── PC, Computer & Hardware Searches ───
  'omprakash pc',
  'Om Prakash PC',
  'OmPrakash PC',
  'omprakash computer',
  'Om Prakash Computer',
  'OmPrakash Computer',
  'omprakash pc build',
  'omprakash computer science',
  'omprakash pc setup',
  'omprakash computer engineer',
  'omprakash computer programmer',
  'omprakash pc specs',
  'omprakash computer developer',
  'omprakash laptop',
  'omprakash tech',
  'omprakash workstation',
  'omprakash system',
  'om prakash pc',
  'om prakash computer',
  'prakash pc',
  'prakash computer',
  'codebyprakash pc',
  'codebyprakash computer',
  'omprakash windows',
  'omprakash linux',
  'omprakash pc developer',
  'omprakash custom pc',
  'omprakash pc build setup',
  'omprakash computer student',
  'omprakash computer coding',
  'omprakash computer hardware',
  'omprakash pc specs build',
  'omprakash computer science engineering',
]

// 2. Gaming, PC & Hardware Keywords
export const GAMING_PC_KEYWORDS = [
  // Gamer & Gaming
  'omprakash gamer',
  'Om Prakash Gamer',
  'OmPrakash Gamer',
  'omprakash gaming',
  'Om Prakash Gaming',
  'OmPrakash Gaming',
  'omprakash pc gamer',
  'Om Prakash PC Gamer',
  'omprakash pro gamer',
  'omprakash esports',
  'CodeByPrakash Gaming',
  'CodeByPrakash Gamer',
  'Quasar Om Gamer',
  'Quasar Om Gaming',
  'quasar_om gamer',
  'quasar_om gaming',
  'Om Prakash game developer',
  'omprakash game dev',
  'omprakash games',
  'omprakash streamer',
  'omprakash gaming setup',
  'om gaming',
  'prakash gamer',
  'prakash gaming',
  'om gamer',
  'omprakash yt gamer',
  'omprakash gaming channel',
  'omprakash gameplay',
  'omprakash live gamer',
  'omprakash gamer odisha',
  'omprakash gamer india',
  'omprakashgamer',
  'omprakashgaming',
  'OMPRAKASH GAMER',
  'OMPRAKASH GAMING',
  'om_prakash_gamer',
  'quasar_om_gamer',
  'Indian PC gamer developer',
  'coder gamer portfolio',
  'gamer software engineer',
  'gaming portfolio website',

  // PC & Computer
  'omprakash pc',
  'Om Prakash PC',
  'OmPrakash PC',
  'omprakash computer',
  'Om Prakash Computer',
  'OmPrakash Computer',
  'omprakash pc build',
  'omprakash computer science',
  'omprakash pc setup',
  'omprakash computer engineer',
  'omprakash computer programmer',
  'omprakash pc specs',
  'omprakash computer developer',
  'omprakash laptop',
  'omprakash tech',
  'omprakash workstation',
  'omprakash system',
  'om prakash pc',
  'om prakash computer',
  'prakash pc',
  'prakash computer',
  'codebyprakash pc',
  'codebyprakash computer',
  'omprakash windows',
  'omprakash linux',
  'omprakash pc developer',
  'omprakash custom pc',
  'omprakash pc build setup',
  'omprakash computer student',
  'omprakash computer coding',
  'omprakash computer hardware',
  'omprakash pc specs build',
  'omprakash computer science engineering',
  'custom PC build developer India',
  'high performance coding workstation',
  'developer PC setup 2026',
]

// 3. Engineering, Degrees & Education
export const EDUCATION_KEYWORDS = [
  // ─── Degrees, Diplomas & Titles ───
  'Computer Science Engineer',
  'Computer Science and Engineering',
  'Computer Science Engineering Student',
  'CSE',
  'CSE Engineer',
  'CSE Student',
  'BTech',
  'B.Tech',
  'B Tech',
  'BTech CSE',
  'BTech CSE Student',
  'B.Tech Computer Science and Engineering',
  'B.Tech CSE 2026',
  'B.Tech CSE 2027',
  'B.Tech CSE 2028',
  'B.Tech CSE Batch 2025-2028',
  'B Tech CS',
  'Bachelor of Technology',
  'Bachelor of Technology Computer Science',
  'Bachelor of Technology in Computer Science and Engineering',
  'Bachelor of Technology CSE',
  'Undergraduate Engineering Student',

  // ─── Comprehensive Diploma CSE & Polytechnic Keywords ───
  'Diploma',
  'Diploma in Computer Science Engineering',
  'Diploma in Computer Science & Engineering',
  'Diploma in Computer Science',
  'Diploma in Computer Engineering',
  'Diploma in CSE',
  'Diploma CSE',
  'Diploma Computer Science',
  'Diploma CS',
  'Diploma Engineering',
  'Diploma 2022',
  'Diploma 2025',
  'Diploma Batch 2022-2025',
  'Diploma CSE Odisha',
  'Diploma in CSE Odisha',
  'Diploma CSE SCTE&VT',
  'Diploma CSE SCTE VT Odisha',
  'Diploma CSE Distinction',
  'Diploma in CSE First Class Distinction',
  'Diploma CSE First Class with Distinction',
  'Diploma CSE Topper',
  'Diploma CSE Syllabus',
  'Diploma CSE Projects',
  'Diploma CSE Final Year Project',
  'Diploma CSE Mini Project',
  'Diploma CSE Major Project',
  'Diploma CSE Lateral Entry',
  'Diploma CSE to BTech CSE',
  'Diploma CSE OJEE',
  'Diploma CSE Resume',
  'Diploma in CSE GCEK',
  'Diploma CSE Student Portfolio',
  'Best Diploma CSE Projects',
  'Diploma CSE Full Stack Developer',
  'Diploma CSE AI ML Developer',
  'Diploma CSE Coding',
  'Diploma CSE Fresher',
  'Diploma CSE Jobs',
  'Diploma CSE Notes',
  'Diploma CSE Books',
  'Diploma CSE Subjects',
  'Diploma CSE Practical Lab',
  'Diploma in CSE 3 Years Program',
  'SCTE&VT CSE Diploma Certificate',
  'Om Prakash Diploma CSE',
  'Om Prakash Behera Diploma CSE',
  'Om Prakash Diploma Computer Science',
  'Diploma Computer Science Engineer',
  'Polytechnic',
  'Polytechnic CSE',
  'Polytechnic in CSE',
  'Polytechnic Computer Science',
  'Polytechnic Computer Science Engineering',
  'Polytechnic Diploma CSE',
  'Polytechnic CSE Odisha',
  'Polytechnic Computer Engineering',
  'Polytechnic Engineering Odisha',
  'Government Polytechnic CSE',
  'Polytechnic Student Portfolio',

  // ─── Current Institution — GCEK (Government College of Engineering Kalahandi) ───
  'GCEK',
  'GCEK Kalahandi',
  'GCEK CSE',
  'GCEK Jaipatna',
  'GCEK Bhawanipatna',
  'GCEK BTech',
  'GCEK Student',
  'GCEK Computer Science',
  'GCEK CSE Department',
  'Government College of Engineering Kalahandi',
  'Government College of Engineering, Kalahandi',
  'GCE Kalahandi',
  'Government College of Engineering Jaipatna',
  'Government Engineering College Kalahandi',
  'GCEK Bandopala',
  'GCEK Campus',
  'GCEK Engineering',
  'GCEK Tech Community',
  'GCEK Coding Club',
  'OM GCEK',
  'PRAKASH GCEK',
  'GCEK PRAKASH',
  'Om Prakash GCEK',
  'Om Prakash Behera GCEK student',
  'GCEK Vendor Om Prakash',

  // ─── University Affiliation — BPUT Odisha ───
  'Biju Patnaik University of Technology',
  'BPUT',
  'BPUT Odisha',
  'BPUT Rourkela',
  'BPUT CSE',
  'BPUT BTech',
  'BPUT Engineering Student',
  'BPUT Computer Science',
  'BPUT Syllabus CSE',
  'BPUT Results CSE',
  'BPUT University Student',

  // ─── State Technical Board — SCTE&VT Odisha ───
  'State Council for Technical Education',
  'State Council for Technical Education and Vocational Training',
  'State Council for Technical Education & Vocational Training',
  'SCTE Odisha',
  'SCTE&VT',
  'SCTE&VT Odisha',
  'SCTE VT Odisha CSE',
  'SCTE&VT Diploma Topper',
  'SCTE&VT First Class Distinction',
  'Directorate of Technical Education & Training Odisha',
  'DTET Odisha',

  // ─── Admission, Lateral Entry & Competitive Exams ───
  'Lateral Entry',
  'Lateral Entry BTech',
  'Lateral Entry CSE',
  'Lateral Entry 2025',
  'Lateral Entry Engineering',
  'Diploma to BTech',
  'Diploma to Degree',
  'Diploma Lateral Entry BTech',
  'Diploma to BTech CSE Lateral Entry',
  'OJEE',
  'Odisha Joint Entrance Examination',
  'OJEE Lateral Entry',
  'OJEE Lateral Entry CSE',
  'OJEE LE Rank',
  'OJEE 2025',
  'OJEE Counselling GCEK',
  'First Class Distinction',
  'First Class Honours',
  'Distinction in Diploma',
  'Academic Excellence',
  'Merit Student',
  'Topper CSE',
  'Top Engineering Student Odisha',

  // ─── Schooling & Foundations ───
  'Matriculation',
  '10th Pass Odisha',
  'Secondary School Examination',
  'BSE Odisha',
  'Board of Secondary Education Odisha',
  'High School Odisha',
  'Schooling Bhadrak',

  // ─── Generic Student / Graduate Categories ───
  'Engineering Student India',
  'Engineering Student Odisha',
  'BTech Student India',
  'BTech Student Odisha',
  'Computer Science Graduate',
  'CS Graduate',
  'CS Graduate India',
  'Computer Science Student',
  'IT Engineer',
  'Information Technology',
  'Engineering Fresher',
  'CSE Fresher',
  'CSE Fresher 2026',
  'CSE Fresher 2027',
  'CSE Fresher 2028',
  'Fresh Graduate CSE',
  'Fresh Graduate Engineer',
  'Engineering Graduate India',
  'Computer Science Degree',
  'CS Degree India',
  'Engineering Degree India',
  'College Student Developer',
  'University Student Developer',
  'Third Year BTech',
  'Second Year BTech',
  'Final Year BTech',
  'Final Year CSE',
  'Student Developer Community',

  // ─── Academic Timeline & Milestones ───
  'Started Coding 2022',
  'First Project 2023',
  'Web Development 2024',
  'BTech CSE 2025',
  'AI ML 2026',
  'Student since 2022',
  '3 years coding experience',
  '3 years development experience',
  '3+ Years Building Production Code',
  'Self-Directed Learning Journey',
  'Student Innovator India',
]

// 3. Professional Titles & Roles
// Covers both formal titles AND informal terms people actually search
export const ROLE_KEYWORDS = [
  // Formal titles
  'Full-Stack Developer',
  'Full Stack Developer',
  'Fullstack Developer',
  'Software Engineer',
  'Software Developer',
  'AI Engineer',
  'ML Engineer',
  'Machine Learning Engineer',
  'Frontend Developer',
  'Front End Developer',
  'Backend Developer',
  'Back End Developer',
  'MERN Stack Developer',
  'MERN Developer',
  'Python Developer',
  'React.js Developer',
  'React Developer',
  'Flask Developer',
  'Node.js Developer',
  'Node Developer',
  'Next.js Developer',
  'Computer Vision Engineer',
  'Deep Learning Specialist',
  'Cyber Security Enthusiast',
  'Web Application Developer',
  'Web Developer',
  'App Developer',

  // Informal terms people actually search
  'Coder',
  'Programmer',
  'Web Dev',
  'Full Stack Coder India',
  'Developer India',
  'Indian Developer',
  'Indian Coder',
  'Indian Programmer',
  'Tech Guy',
  'Coding Expert',
  'Freelance Coder',
  'Freelance Programmer',
  'Self-Taught Developer',
  'Student Developer India',
  'Junior Developer',
  'Entry Level Developer',
  'Fresher Developer',
  'Remote Developer',
  'Remote Developer India',
]

// 4. Artificial Intelligence, Machine Learning & Vision
export const AI_ML_KEYWORDS = [
  // Core AI/ML
  'Artificial Intelligence',
  'Machine Learning',
  'Deep Learning',
  'Generative AI',
  'GenAI',
  'AI Developer',
  'AI Projects',
  'AI Applications',
  'AI Solutions',
  'AI Automation',
  'AI Software',
  'Intelligent Systems',

  // Computer Vision
  'Computer Vision',
  'MediaPipe',
  'OpenCV',
  'Image Processing',
  'Video Analysis',
  'Face Detection',
  'Face Recognition',
  'Facial Recognition System',
  'Object Detection',
  'Object Tracking',
  'Real-Time Object Tracking',
  'Image Classification',
  'Image Segmentation',
  'Pose Estimation',
  'Hand Tracking',
  'Gesture Recognition AI',
  'Augmented Reality AI',
  'AR Computer Vision',

  // Neural Network Architectures
  'Convolutional Neural Networks',
  'CNN',
  'Recurrent Neural Networks',
  'RNN',
  'Long Short-Term Memory',
  'LSTM',
  'Bidirectional LSTM',
  'Transformer Models',
  'Attention Mechanism',
  'GAN',
  'Generative Adversarial Networks',
  'Autoencoders',
  'Neural Network',
  'Deep Neural Network',
  'Transfer Learning',
  'Fine Tuning AI Models',

  // LLM & NLP
  'Large Language Models',
  'LLM',
  'Natural Language Processing',
  'NLP',
  'GPT',
  'Chatbot Development',
  'AI Chatbot',
  'Text Classification',
  'Sentiment Analysis',
  'Text Generation',
  'RAG',
  'Retrieval Augmented Generation',
  'Prompt Engineering',
  'LLM Fine Tuning',
  'Local LLM',
  'Ollama AI',

  // Frameworks & Libraries
  'TensorFlow',
  'TensorFlow 2',
  'Keras',
  'PyTorch',
  'Scikit-learn',
  'Sklearn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Seaborn',
  'SciPy',
  'Streamlit',
  'Hugging Face',
  'Transformers Library',
  'ONNX',
  'OpenAI API',
  'LangChain',
  'face-api.js',

  // Detection Models
  'YOLOv8',
  'YOLOv5',
  'YOLO Object Detection',
  'SSD Object Detection',
  'Haar Cascades',
  'Dlib',

  // ML Techniques
  'Supervised Learning',
  'Unsupervised Learning',
  'Reinforcement Learning',
  'Classification',
  'Regression',
  'Clustering',
  'Support Vector Machine',
  'SVM',
  'SVC',
  'Random Forest',
  'Decision Tree',
  'K-Nearest Neighbors',
  'KNN',
  'Gradient Boosting',
  'XGBoost',
  'Feature Engineering',
  'Data Preprocessing',
  'Model Training',
  'Model Evaluation',
  'Cross Validation',
  'Hyperparameter Tuning',
  'TF-IDF',
  'Cosine Similarity',
  'Collaborative Filtering',
  'Content Based Filtering',
  'Recommendation Engine',

  // Specific Project Terms
  'Face Emotion Detector',
  'Emotion Detection AI',
  'Hand Gesture Recognition',
  'AI Healthcare System',
  'Medicine Recommender System',
  'Movie Recommender System',
  'Indian Sign Language Recognition',
  'ISL Translator',
  'Sign Language AI',
  'Crowd Density Monitoring',
  'Crowd Analysis AI',
  'Stock Price Prediction',
  'Stock Market AI',
  'Financial AI',
  'Exoplanet Detection Machine Learning',
  'Astrophysics AI',
  'Time Series Forecasting',
  'Predictive Analytics',
  'Data Science',
  'Data Analytics',
  'Data Visualization',
  'Big Data',
]

// 5. Web Development & Programming Stack
export const TECH_STACK_KEYWORDS = [
  // Frontend Frameworks & Libraries
  'React.js',
  'React',
  'React 19',
  'React Hooks',
  'React Router',
  'Next.js',
  'Next.js 14',
  'Vue.js',
  'Angular',
  'Svelte',
  'Framer Motion',
  'GSAP',
  'Three.js',
  'Redux',
  'Context API',
  'State Management',

  // Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Python 3',
  'PHP',
  'Java',
  'C',
  'C++',
  'SQL',
  'Bash',
  'Shell Scripting',

  // Backend
  'Node.js',
  'Express.js',
  'Flask',
  'FastAPI',
  'Django',
  'REST API Design',
  'RESTful API',
  'GraphQL',
  'WebSocket',
  'Microservices',
  'Server Side Rendering',
  'SSR',
  'API Development',
  'Backend Development',
  'Serverless Functions',
  'Cloudflare Workers',
  'Edge Computing',

  // Markup & Styling
  'HTML5',
  'HTML',
  'CSS3',
  'CSS',
  'Sass',
  'SCSS',
  'Less',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Styled Components',
  'CSS Modules',
  'CSS Grid',
  'Flexbox',
  'Responsive Web Design',
  'Mobile First Design',
  'UI UX Design',
  'Web Design',
  'Modern Web Design',
  'Claymorphism',
  'Glassmorphism',
  'Neumorphism',
  'Dark Mode',
  'Animations CSS',
  'Web Animations',

  // Databases
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'SQLite',
  'Firebase',
  'Supabase',
  'Redis',
  'NoSQL',
  'Database Design',
  'Schema Design',
  'ORM',
  'Mongoose',
  'Prisma',
  'Sequelize',

  // DevOps & Deployment
  'Git',
  'GitHub',
  'GitLab',
  'Version Control',
  'CI CD',
  'Docker',
  'Kubernetes',
  'AWS',
  'Google Cloud',
  'Azure',
  'Vercel',
  'Netlify',
  'Heroku',
  'DigitalOcean',
  'Linux',
  'Ubuntu',
  'Nginx',
  'Apache',
  'Cloud Deployment',
  'Web Hosting',

  // Build Tools
  'Vite',
  'Webpack',
  'Babel',
  'ESLint',
  'Prettier',
  'npm',
  'Yarn',
  'pnpm',
  'Package Manager',

  // Blockchain
  'Solidity',
  'Blockchain Development',
  'Blockchain',
  'Web3',
  'Web3 Developer',
  'IPFS',
  'Smart Contracts',
  'Ethereum',
  'DApp',
  'Decentralized Application',
  'Cryptocurrency',
  'NFT',

  // AI Infra
  'Ollama',
  'CUDA',
  'GGUF Quantization',
  'GPU Programming',
  'VRAM Optimization',
  'Model Deployment',

  // Architecture
  'Progressive Web App',
  'PWA',
  'Single Page Application',
  'SPA',
  'Jamstack',
  'Headless CMS',
  'Full Stack Application',
  'Monorepo',
  'Clean Architecture',
  'Design Patterns',
  'MVC',
  'MVVM',
  'Component Based Architecture',

  // Testing
  'Unit Testing',
  'Integration Testing',
  'Jest',
  'Mocha',
  'Cypress',
  'Selenium',
  'Test Driven Development',
  'TDD',

  // Design Tools
  'Figma',
  'Blender',
  'Canva',
  'Adobe XD',
  'Photoshop',
  'UI Design',
  'Wireframing',
  'Prototyping',
]

// 6. Computer Science Fundamentals & Cyber Security
export const CS_SECURITY_KEYWORDS = [
  // CS Fundamentals
  'Data Structures and Algorithms',
  'DSA',
  'Data Structures',
  'Algorithms',
  'Competitive Programming',
  'Coding Interview',
  'LeetCode',
  'Problem Solving',
  'System Design',
  'Low Level Design',
  'High Level Design',
  'Object Oriented Programming',
  'OOP',
  'Functional Programming',
  'Software Architecture',
  'Design Patterns',
  'SOLID Principles',
  'Operating Systems',
  'Computer Networks',
  'Database Management System',
  'DBMS',
  'Compiler Design',
  'Theory of Computation',
  'Discrete Mathematics',

  // Cyber Security
  'Cyber Security',
  'Cybersecurity',
  'Information Security',
  'InfoSec',
  'Ethical Hacking',
  'Penetration Testing',
  'Pen Testing',
  'Bug Bounty',
  'Vulnerability Assessment',
  'Security Audit',
  'System Security',
  'Network Security',
  'Web Security',
  'Application Security',
  'OWASP',
  'OWASP Top 10',
  'SQL Injection',
  'XSS',
  'Cross Site Scripting',
  'CSRF',
  'Firewall',
  'VPN',
  'Encryption',
  'Cryptography',
  'SSL TLS',
  'HTTPS',
  'Authentication',
  'Authorization',
  'JWT',
  'OAuth',
  'Two Factor Authentication',
  '2FA',
  'Password Hashing',
  'bcrypt',
  'Security Best Practices',
  'Secure Coding',
  'Kali Linux',
  'Wireshark',
  'Nmap',
  'Metasploit',
  'Burp Suite',

  // Project-specific
  'DNS Switcher',
  'Privacy Dashboard',
  'Secure Authentication',
  'Computer Lab Management System',
  'CLMS',
  'Privacy Protection',
  'Data Privacy',
  'Digital Privacy',
  'Anti Surveillance',
  'Telemetry Blocking',
]

// 7. Location, Regional & Freelance
export const LOCATION_FREELANCE_KEYWORDS = [
  // ─── Native Place & Hometown (Bhadrak District, Odisha) ───
  'Web Developer Bhadrak',
  'Developer Bhadrak',
  'Software Engineer Bhadrak',
  'Coder Bhadrak',
  'Programmer Bhadrak',
  'Bhadrak Odisha Developer',
  'Bhadrak Tech Talent',
  'Bhadrak City Developer',
  'Bhadrak Town',
  'Dhamra',
  'Basudevpur',
  'Chandbali',
  'Bonth',
  'Bhandaripokhari',
  'Tihidi',
  'Charampa',
  'Bhadrak College',
  'Best Developer in Bhadrak',
  'Top Coder in Bhadrak',

  // ─── College & Campus Location (Kalahandi District, Odisha) ───
  'Developer Kalahandi',
  'Web Developer Kalahandi',
  'Software Engineer Kalahandi',
  'Developer Bhawanipatna',
  'Web Developer Bhawanipatna',
  'Bhawanipatna Kalahandi',
  'Developer Jaipatna',
  'GCEK Jaipatna Location',
  'Kalahandi Tech Talent',
  'Junagarh',
  'Kesinga',
  'Dharmagarh',
  'Western Odisha Developer',
  'KBK Region Developer',
  'Kalahandi Engineering',

  // ─── Major Odisha Cities & Tech Hubs ───
  'Web Developer Odisha',
  'Developer Odisha',
  'Software Engineer Odisha',
  'AI Developer Odisha',
  'Coder Odisha',
  'Programmer Odisha',
  'Developer Bhubaneswar',
  'Web Developer Bhubaneswar',
  'Software Engineer Bhubaneswar',
  'Infocity Bhubaneswar',
  'Smart City Bhubaneswar',
  'Developer Cuttack',
  'Web Developer Cuttack',
  'Silver City Cuttack',
  'Developer Balasore',
  'Web Developer Balasore',
  'Baleswar',
  'Developer Berhampur',
  'Brahmapur',
  'Developer Sambalpur',
  'Web Developer Sambalpur',
  'Developer Rourkela',
  'Steel City Rourkela',
  'Developer Puri',
  'Developer Baripada',
  'Developer Angul',
  'Developer Dhenkanal',
  'Developer Jajpur',
  'Developer Keonjhar',
  'Developer Jharsuguda',
  'Developer Mayurbhanj',
  'Freelancer Odisha',
  'IT Professional Odisha',
  'Tech Talent Odisha',
  'Odisha Tech Community',
  'Odisha Developer Network',
  'Odisha Startup Ecosystem',

  // ─── Odia Identity & Regional Culture ───
  'Odia Developer',
  'Odia Coder',
  'Odia Programmer',
  'Odia Software Engineer',
  'Odia Full Stack Developer',
  'Odia AI Engineer',
  'Odia Tech Guy',
  'Odia Student Developer',
  'Odia Tech Enthusiast',
  'Best Odia Developer',
  'Top Odia Coder',
  'Odia Youth in Tech',
  'Utkal Developer',
  'Kalinga Developer',
  'Odia Language Developer',
  'Odia Tech Creator',

  // ─── India / National Identity ───
  'Developer India',
  'Web Developer India',
  'Software Engineer India',
  'AI Developer India',
  'Indian Software Engineer',
  'Indian Full Stack Developer',
  'Indian AI Engineer',
  'Indian Web Developer',
  'Indian Python Developer',
  'Indian React Developer',
  'Indian Coder',
  'Indian Programmer',
  'Indian Tech Talent',
  'Indian Student Innovator',
  'Best Developer India',
  'Top Developer India',
  'Young Developer India',
  'Made in India Software',
  'Indian Tech Ecosystem',
  'Eastern India Developer',

  // ─── Freelance, Remote & Hiring Intent ───
  'Freelance Web Developer India',
  'Freelance Developer India',
  'Freelance AI Developer',
  'Freelance Python Developer',
  'Freelance React Developer',
  'Freelance Full Stack Developer',
  'Freelance Software Engineer',
  'Freelance MERN Developer',
  'Freelancer for Hire',
  'Hire Remote Developer',
  'Hire Remote Developer India',
  'Hire Frontend Developer India',
  'Hire Backend Developer India',
  'Hire Python Developer India',
  'Hire React Developer India',
  'Hire MERN Developer India',
  'Hire AI Developer India',
  'Hire ML Engineer India',
  'Hire Web Developer from Odisha',
  'Affordable Developer India',
  'Cheap Developer India',
  'Budget Developer India',
  'Contract Developer India',
  'Outsource Development India',
  'Outsource Web Development',
  'Outsource AI Development',
  'Open for Work 2026',
  'Available for Hire',
  'Looking for Opportunities',
  'Open to Freelance',
  'Open to Collaboration',
  'Startup Developer',
  'MVP Developer',
  'Prototype Developer',
  'Website Builder for Hire',
  'App Builder for Hire',
  'Consultant Web Developer',
  'Remote Software Engineer India',
]

// 8. Featured Projects
export const PROJECT_KEYWORDS = [
  'AR Hand Gesture Canvas',
  'MRS-AI Healthcare',
  'Movie Recommender System',
  'Privacy Dashboard System',
  'Open E-Commerce Platform',
  'GCEK Vendor',
  'Resume Builder React',
  'Attend True Analytic',
  'Hand Gesture Controller',
  'Public DNS Switcher',
  'Computer LMS LocalHost',
  'Odisha Tourist Management System',
  'ISRO Exoplanet ML',
  'AttendTrue Analytics SIH 2025',
  'UnVoiced Sign Language AI',
  'StadiumAI Vision',
  'Local LLM ChatUI',
  'Stock Predictor AI',
  'SmartPlacement',
  'Biometric Face Attendance',
  'EmoSense Face Emotion Detector',
]

// 9. Long-Tail SEO & Question-Based Keywords
export const LONG_TAIL_KEYWORDS = [
  // Portfolio / Discovery
  'best developer portfolio 2026',
  'best developer portfolio website',
  'best portfolio website design',
  'top developer portfolio India 2026',
  'creative developer portfolio',
  'animated portfolio website',
  'react portfolio website',
  'modern portfolio website 2026',
  'portfolio website inspiration',
  'developer personal website',
  'software engineer portfolio website',
  'machine learning engineer portfolio',
  'AI engineer portfolio website',
  'computer science student portfolio website',
  'CSE student portfolio',
  'BTech CSE student projects',
  'BTech student portfolio website',
  'engineering student portfolio India',
  'fresher developer portfolio website',
  'junior developer portfolio website',
  'programmer portfolio website',
  'coder portfolio website',

  // Hiring Intent
  'hire full stack developer India',
  'hire AI developer from India',
  'hire web developer India cheap',
  'hire react developer freelance',
  'hire python developer freelance India',
  'hire MERN stack developer for startup',
  'MERN stack developer for hire',
  'python flask developer India',
  'affordable web developer India',
  'best freelance developer India',
  'freelance AI ML developer',
  'developer available for remote work',
  'remote developer India for startup',
  'hire developer for MVP',
  'hire developer for website',
  'hire developer for app',
  'hire developer for AI project',
  'need developer for my project',
  'looking for developer for my startup',
  'find developer for project',

  // Google Question Queries ("how to" / "what is")
  'how to build AI healthcare system',
  'how to build medicine recommender system',
  'how to build movie recommender system python',
  'how to build hand gesture recognition',
  'how to build face emotion detector',
  'how to build stock price predictor python',
  'how to detect exoplanets machine learning',
  'how to build crowd monitoring system',
  'how to build sign language translator AI',
  'how to build ecommerce website react',
  'how to build portfolio website react',
  'how to run LLM locally',
  'how to build DNS switcher',
  'how to build privacy dashboard',
  'how to build attendance system face recognition',
  'how to build resume builder react',
  'how to build campus marketplace',

  // Project-Specific Searches
  'computer vision projects GitHub',
  'hand gesture recognition project',
  'hand gesture recognition project GitHub',
  'Indian sign language detection AI',
  'Indian sign language recognition project',
  'YOLOv8 crowd monitoring project',
  'YOLOv8 project ideas',
  'LSTM stock prediction project',
  'LSTM stock price prediction GitHub',
  'blockchain carbon credit platform',
  'carbon credit blockchain project',
  'ISRO hackathon project',
  'ISRO BAH 2026 project',
  'exoplanet detection project',
  'Smart India Hackathon 2025 projects',
  'SIH 2025 project ideas',
  'SIH project GitHub',
  'AI projects for engineering students',
  'machine learning project ideas 2026',
  'deep learning project ideas',
  'computer vision project ideas',
  'python project ideas for students',
  'react project ideas 2026',
  'full stack project ideas',
  'cyber security project ideas',
  'best open source projects 2026',
  'computer science engineering projects',
  'final year project CSE',
  'BTech final year project ideas',
  'diploma project ideas computer science',
  'mini project ideas CSE',
  'major project ideas CSE',

  // Location-Based
  'full stack web developer Odisha',
  'best developer in Odisha',
  'web developer near me India',
  'freelance developer near me',
  'developer in Bhadrak',
  'developer in Kalahandi',
  'developer in Bhubaneswar',

  // Trending Tech Searches 2026
  'generative AI projects 2026',
  'LLM projects GitHub 2026',
  'best AI projects 2026',
  'best react projects 2026',
  'trending GitHub projects 2026',
  'AI tools 2026',
  'web development trends 2026',
  'AI development trends 2026',
  'best programming languages 2026',
  'full stack developer roadmap 2026',
  'AI engineer roadmap 2026',
]

/**
 * ─── MASTER KEYWORD LIST ───
 * Combines all categories and the easy words, removing any duplicates.
 */
export const ALL_KEYWORDS = Array.from(
  new Set([
    ...EASY_WORDS,
    ...IDENTITY_KEYWORDS,
    ...GAMING_PC_KEYWORDS,
    ...EDUCATION_KEYWORDS,
    ...ROLE_KEYWORDS,
    ...AI_ML_KEYWORDS,
    ...TECH_STACK_KEYWORDS,
    ...CS_SECURITY_KEYWORDS,
    ...LOCATION_FREELANCE_KEYWORDS,
    ...PROJECT_KEYWORDS,
    ...LONG_TAIL_KEYWORDS,
  ])
)

/**
 * ─── PAGE-SPECIFIC KEYWORD COLLECTIONS ───
 */

export const HOME_PAGE_KEYWORDS = ALL_KEYWORDS

export const PROJECTS_PAGE_KEYWORDS = Array.from(
  new Set([
    ...EASY_WORDS,
    ...PROJECT_KEYWORDS,
    ...AI_ML_KEYWORDS,
    ...TECH_STACK_KEYWORDS,
    'Projects Showcase',
    'Open Source GitHub Repositories',
    'Full-Stack Portfolio Projects',
    'AI Systems Demonstration',
  ])
)

export const ABOUT_PAGE_KEYWORDS = Array.from(
  new Set([
    ...EASY_WORDS,
    ...IDENTITY_KEYWORDS,
    ...EDUCATION_KEYWORDS,
    ...ROLE_KEYWORDS,
    ...LOCATION_FREELANCE_KEYWORDS,
    'About Om Prakash Behera',
    'Who is Om Prakash Behera',
    'Om Prakash Behera Biography',
    'Om Prakash Behera Story',
    'CSE Student Background',
    'BTech Experience Odisha',
    'Diploma to Degree Journey',
    'GCEK Kalahandi Student',
    'Bhadrak Developer Story',
    'Character Stats Om Prakash',
    'Self-Taught Engineering Skills',
    'Developer from Odisha India',
    'Odia Developer Profile',
    'CodeByPrakash Bio',
    'Quasar Om Profile',
    'Academic Credentials',
    'Coding Journey 2022 to 2026',
  ])
)

export const CONTACT_PAGE_KEYWORDS = Array.from(
  new Set([
    ...EASY_WORDS,
    ...LOCATION_FREELANCE_KEYWORDS,
    'Contact Om Prakash Behera',
    'Hire Om Prakash Behera',
    'Hire Om Prakash',
    'Hire CodeByPrakash',
    'Email Om Prakash Behera',
    'omprakashbehera.cse@gmail.com',
    'How to Contact Om Prakash Behera',
    'Om Prakash Behera WhatsApp',
    'Om Prakash Behera Phone',
    'Om Prakash Behera Message',
    'Om Prakash Behera Freelance',
    'Freelance Consultation Odisha',
    'Hire Remote Full Stack Developer India',
    'Hire AI ML Engineer India',
    'Hire React Developer Odisha',
    'Send Message to Developer',
    'Software Project Collaboration',
    'Student Developer for Hire',
    'Affordable Web Developer India',
  ])
)

export const BLOG_PAGE_KEYWORDS = Array.from(
  new Set([
    ...EASY_WORDS,
    ...AI_ML_KEYWORDS,
    ...TECH_STACK_KEYWORDS,
    ...CS_SECURITY_KEYWORDS,
    'Technical Blog',
    'AI Articles',
    'Machine Learning Engineering Blog',
    'Computer Vision Tutorials',
    'MediaPipe Real-Time Canvas',
    'Emotion AI Research',
    '3D Claymorphism Web Design',
    'DNS Switcher Guide',
    'Engineering Insights',
    'Developer Blog Odisha',
    'CodeByPrakash Articles',
    'ISRO BAH 2026 PS-07',
    'SIH 2025 Team CodeNova',
    'MRS-AI Medicine Recommender',
    'AR Hand Gesture Canvas',
    'UnVoiced ISL Translator',
    'Public DNS Switcher',
    'Biometric Face Recognition Attendance',
    'StadiumAI Crowd Density',
    'Stock Market LSTM Forecasting',
    'Local LLM Quantization GGUF',
    'SmartPlacement Campus Predictor',
    'Odisha Tourism 3NF Database',
  ])
)

/**
 * ─── PER-ARTICLE TAILORED SEO KEYS, LINKS & SEARCH QUERIES ───
 */
export const BLOG_POSTS_SEO = {
  'isro-bah-2026-exoplanet-detection-ml': {
    slug: 'isro-bah-2026-exoplanet-detection-ml',
    canonicalUrl: 'https://omprakashbehera.me/blog/isro-bah-2026-exoplanet-detection-ml',
    githubUrl: 'https://github.com/CodeByPrakash/ISRO_PS07',
    category: 'AI & ML',
    primaryKeywords: [
      'ISRO BAH 2026 PS-07',
      'ISRO Bharatiya Antariksh Hackathon Problem Statement 07',
      'Exoplanet Detection Machine Learning',
      'Kepler DR25 light curve transit photometry',
      'BLS Box Least Squares periodogram Python',
      '1D CNN exoplanet classification',
      'astrophysics machine learning project',
      'Wotan spline light curve flattening',
      'CodeByPrakash ISRO_PS07',
      'deep learning exoplanet transit detection',
      'Kepler TESS lightkurve tutorial',
      'astronomy AI research paper India',
    ],
  },
  'sih-2025-attendtrue-analytic': {
    slug: 'sih-2025-attendtrue-analytic',
    canonicalUrl: 'https://omprakashbehera.me/blog/sih-2025-attendtrue-analytic',
    githubUrl: 'https://github.com/CodeByPrakash/AttendTrue-Analytic',
    category: 'AI & Full-Stack',
    primaryKeywords: [
      'AttendTrue Analytics',
      'AttendTrue SIH 2025',
      'Smart India Hackathon 2025 Team CodeNova',
      'AI smart attendance tracking system',
      'computer vision facial recognition attendance',
      'anti-spoofing liveness detection Python',
      'Next.js institutional analytics dashboard',
      'student attendance analytics predictive modeling',
      'Team CodeNova SIH selection',
      'automated proxy prevention attendance system',
      'institutional attendance AI hackathon project India',
    ],
  },
  'mrs-ai-medicine-recommender-system': {
    slug: 'mrs-ai-medicine-recommender-system',
    canonicalUrl: 'https://omprakashbehera.me/blog/mrs-ai-medicine-recommender-system',
    githubUrl: 'https://github.com/CodeByPrakash/MRS-AI',
    category: 'AI & Data',
    primaryKeywords: [
      'MRS-AI Medicine Recommender System',
      'YOUTH@2050 1st Prize Winner Project',
      'AI healthcare clinical symptom diagnosis',
      'Support Vector Classifier SVC disease prediction',
      'multi-class symptom classification Python Flask',
      'pharmaceutical recommendation engine',
      'CodeByPrakash MRS-AI',
      'medicine recommendation system machine learning',
      'clinical triage AI system India',
      '7000 Rs prize pool winning software expo',
    ],
  },
  'ar-hand-gesture-canvas-mediapipe': {
    slug: 'ar-hand-gesture-canvas-mediapipe',
    canonicalUrl: 'https://omprakashbehera.me/blog/ar-hand-gesture-canvas-mediapipe',
    liveUrl: 'https://arhandgesture.vercel.app/',
    githubUrl: 'https://github.com/CodeByPrakash/AR_HandGesture',
    category: 'Computer Vision',
    primaryKeywords: [
      'AR Hand Gesture Canvas MediaPipe',
      'Google MediaPipe 21 hand landmarks tracking',
      'touchless virtual drawing canvas JavaScript',
      'Bézier curve air drawing canvas React',
      'computer vision gesture control web',
      'arhandgesture vercel app',
      'hand tracking air canvas OpenCV MediaPipe',
      'CodeByPrakash AR_HandGesture',
      'zero latency browser computer vision',
    ],
  },
  'unvoiced-sign-language-translator-opencv': {
    slug: 'unvoiced-sign-language-translator-opencv',
    canonicalUrl: 'https://omprakashbehera.me/blog/unvoiced-sign-language-translator-opencv',
    githubUrl: 'https://github.com/CodeByPrakash/UnVoiced',
    category: 'Computer Vision',
    primaryKeywords: [
      'UnVoiced Indian Sign Language AI Translator',
      'ISL gesture recognition OpenCV Python',
      'YCrCb skin color segmentation hand contour',
      'sign language to speech synthesis pyttsx3',
      'accessibility deaf mute communication AI',
      'real-time sign language alphabet recognition',
      'CodeByPrakash UnVoiced',
      'OpenCV Indian sign language translator',
      'computer vision accessibility tool India',
    ],
  },
  'public-dns-switcher-system-utility': {
    slug: 'public-dns-switcher-system-utility',
    canonicalUrl: 'https://omprakashbehera.me/blog/public-dns-switcher-system-utility',
    githubUrl: 'https://github.com/CodeByPrakash/Public_DNS_Switcher',
    category: 'Cyber Security',
    primaryKeywords: [
      'Public DNS Switcher Windows',
      'Windows TCP IP netsh DNS automation',
      'Cloudflare Google Quad9 DNS switcher',
      'live ICMP socket latency benchmark Python Flask',
      'network adapter DNS override script',
      'fast DNS benchmark tool Windows',
      'CodeByPrakash Public_DNS_Switcher',
      'cyber security DNS leak protection utility',
    ],
  },
  'simple-face-recognition-attendance-system': {
    slug: 'simple-face-recognition-attendance-system',
    canonicalUrl: 'https://omprakashbehera.me/blog/simple-face-recognition-attendance-system',
    githubUrl: 'https://github.com/CodeByPrakash/Simple_FaceRecoginition_Attendance_Sys',
    category: 'AI & ML',
    primaryKeywords: [
      'Biometric Face Recognition Attendance System',
      'Haar Cascade dlib 128D deep facial embeddings',
      'contactless classroom attendance logger SQLite',
      'real-time face recognition Python OpenCV',
      'proxy attendance prevention computer vision',
      'CodeByPrakash Simple_FaceRecoginition_Attendance_Sys',
      'biometric attendance software engineer project',
    ],
  },
  'stadium-ai-crowd-density-computer-vision': {
    slug: 'stadium-ai-crowd-density-computer-vision',
    canonicalUrl: 'https://omprakashbehera.me/blog/stadium-ai-crowd-density-computer-vision',
    githubUrl: 'https://github.com/CodeByPrakash/StadiumAI-C4',
    category: 'Computer Vision',
    primaryKeywords: [
      'StadiumAI Crowd Density Monitoring',
      'homography perspective transform bird eye view mapping',
      'YOLOv8 pedestrian head tracking surveillance',
      'crowd surge bottleneck detection OpenCV PyTorch',
      'stadium safety crowd crush alert computer vision',
      'CodeByPrakash StadiumAI-C4',
      'TensorRT real-time surveillance analytics',
    ],
  },
  'stock-market-price-prediction-lstm': {
    slug: 'stock-market-price-prediction-lstm',
    canonicalUrl: 'https://omprakashbehera.me/blog/stock-market-price-prediction-lstm',
    githubUrl: 'https://github.com/CodeByPrakash/stock_price_prediction_application',
    category: 'AI & ML',
    primaryKeywords: [
      'Stock Market Price Prediction LSTM',
      'Bidirectional LSTM PyTorch time series forecasting',
      'RSI MACD NATR financial feature engineering',
      'non-stationary time series deep learning',
      'stock trend forecasting neural network',
      'CodeByPrakash stock_price_prediction_application',
      'quantitative finance machine learning Python',
    ],
  },
  'local-llm-cuda-quantization-optimization': {
    slug: 'local-llm-cuda-quantization-optimization',
    canonicalUrl: 'https://omprakashbehera.me/blog/local-llm-cuda-quantization-optimization',
    githubUrl: 'https://github.com/CodeByPrakash/Local-LLM-ChatUI',
    category: 'AI & Data',
    primaryKeywords: [
      'Local LLM CUDA Optimization',
      'GGUF 4-bit quantization Q4_K_M Ollama',
      'consumer GPU VRAM layer offloading',
      'Flash Attention 2 local AI inference',
      'Server-Sent Events SSE React chat UI LLM',
      'Ollama CUDA Improver CodeByPrakash',
      'run Llama 3 locally NVIDIA GPU mid-tier',
    ],
  },
  'smart-placement-campus-prediction-ml': {
    slug: 'smart-placement-campus-prediction-ml',
    canonicalUrl: 'https://omprakashbehera.me/blog/smart-placement-campus-prediction-ml',
    githubUrl: 'https://github.com/CodeByPrakash/SmartPlacement',
    category: 'Web Architecture',
    primaryKeywords: [
      'SmartPlacement Campus Recruitment Predictor',
      'supervised learning placement probability scoring',
      'engineering college skill gap analytics',
      'Random Forest feature importance campus hiring',
      'custom student preparation roadmap generator',
      'CodeByPrakash SmartPlacement',
      'college placement readiness predictor AI',
    ],
  },
  'odisha-tourism-management-database-architecture': {
    slug: 'odisha-tourism-management-database-architecture',
    canonicalUrl: 'https://omprakashbehera.me/blog/odisha-tourism-management-database-architecture',
    githubUrl: 'https://github.com/CodeByPrakash/OTM',
    category: 'Web Architecture',
    primaryKeywords: [
      'Odisha Tourism Management System OTM',
      '3NF database normalization enterprise schema',
      'ACID transaction locks concurrency PHP MySQL',
      'Computer Lab Management System LMS',
      'Role-Based Access Control RBAC database design',
      'CodeByPrakash OTM LMS',
      'relational database architecture case study',
    ],
  },
}

/**
 * Retrieves all tailored SEO metadata and keyword keys for a specific blog article.
 * @param {string} slug - The article slug
 * @returns {object} The complete SEO configuration object
 */
export function getBlogPostSeo(slug) {
  const data = BLOG_POSTS_SEO[slug] || {
    slug,
    canonicalUrl: `https://omprakashbehera.me/blog/${slug}`,
    category: 'Engineering',
    primaryKeywords: ['Om Prakash Behera', 'CodeByPrakash', 'Engineering Article'],
  }

  const combinedKeywords = Array.from(
    new Set([
      ...data.primaryKeywords,
      ...EASY_WORDS.slice(0, 15),
      'Om Prakash Behera',
      'CodeByPrakash',
      'Computer Science Engineer',
      'Odisha Developer',
      'Technical Article',
    ])
  )

  return {
    ...data,
    keywords: combinedKeywords,
  }
}

export const ACHIEVEMENTS_PAGE_KEYWORDS = Array.from(
  new Set([
    ...EASY_WORDS,
    ...EDUCATION_KEYWORDS,
    'Achievements and Honors',
    'Smart India Hackathon 2025',
    'SIH 2025 Team CodeNova',
    'AttendTrue Analytics SIH 2025 Project',
    'YOUTH@2050 1st Prize Winner',
    'YOUTH@2050 Software Exhibition',
    'District Level Project Software Winner 2024',
    '7000 Rs Prize Pool Winner',
    'Medicine Recommender System 1st Prize',
    'MRS-AI Award Winning Project',
    'BAH 2026 ISRO PS-07',
    'Bharatiya Antariksh Hackathon 2026',
    'ISRO Exoplanet Detection Machine Learning',
    'BTech CSE Lateral Entry GCEK',
    'GCEK Merit Admission',
    'Diploma First Class Distinction SCTE&VT',
    'Diploma in CSE Distinction Honours',
    '100+ GitHub Repositories Milestone',
    'Open Source Milestones CodeByPrakash',
    'Engineering Credentials Odisha',
    'Hackathon Winner India',
    'Student Developer Awards India',
    'Government College of Engineering Kalahandi Awards',
    'Engineering Student Achievements Odisha',
    'AI Project Competition Winner',
  ])
)

export const NOT_FOUND_PAGE_KEYWORDS = [
  '404 Page Not Found',
  'Error 404',
  'Om Prakash Behera Portfolio',
  'Return Home',
]

/**
 * ─── HELPER FUNCTIONS ───
 */

/**
 * Formats a list of keywords or string into a clean, deduplicated, comma-separated string.
 * @param {string[] | string} customKeywords - Additional keywords to include
 * @param {boolean} includeEasyWords - Whether to include the EASY_WORDS array (default: true)
 * @returns {string} Comma-separated keyword string
 */
export function formatKeywords(customKeywords = [], includeEasyWords = true) {
  let combined = []

  if (includeEasyWords) {
    combined.push(...EASY_WORDS)
  }

  if (Array.isArray(customKeywords)) {
    combined.push(...customKeywords)
  } else if (typeof customKeywords === 'string' && customKeywords.trim().length > 0) {
    const splitWords = customKeywords.split(',').map(w => w.trim()).filter(Boolean)
    combined.push(...splitWords)
  }

  // If nothing was passed, fallback to ALL_KEYWORDS
  if (combined.length === 0) {
    combined = ALL_KEYWORDS
  }

  // Deduplicate while preserving order
  const unique = Array.from(new Set(combined))
  return unique.join(', ')
}

export default {
  EASY_WORDS,
  ALL_KEYWORDS,
  GAMING_PC_KEYWORDS,
  HOME_PAGE_KEYWORDS,
  PROJECTS_PAGE_KEYWORDS,
  ABOUT_PAGE_KEYWORDS,
  CONTACT_PAGE_KEYWORDS,
  BLOG_PAGE_KEYWORDS,
  BLOG_POSTS_SEO,
  getBlogPostSeo,
  ACHIEVEMENTS_PAGE_KEYWORDS,
  NOT_FOUND_PAGE_KEYWORDS,
  LONG_TAIL_KEYWORDS,
  formatKeywords,
}
